export const withholdingTaxData = {
  saleOfGoodsByCompany: 4,
  saleOfGoodsbyIndividualAndAop: 4.50,
  servicesByCompany: 8,
  servicesbyIndividualAndAop: 10,
  servicesByExportServices: 1,
  servicesByAdvertisementServices: 1.50,
  servicesByTransportServices: 3,
  servicesByFreightForwardServices: 3,
  servicesByAirCargoServices: 3,
  servicesByCourierServices: 3,
  servicesByManPowerOutsourceServices: 3,
  servicesByHotelServices: 3,
  servicesBySecurityServices: 3,
  servicesBySoftwareDevelopmentServices: 3,
  servicesByItServicesServices: 3,
  servicesByTrackingServices: 3,
  servicesByShareRegisterdServices: 3,
  servicesByEngineeringServices: 3,
//   servicesByExportServices: "",
  servicesByCarRentalServices: 3,
  servicesByBuildingMaintenanceServices: 3,
  servicesByInspectionServices: 3,
  servicesByCertificationServices: 3,
  servicesByTestingServices: 3,
  servicesByTrainingServices: 3,
  servicesByWarehouseServices: 3,
  servicesByAssestsManagementServices: 3,
  servicesByDataServices: 3,
  servicesByTelecommunicationServices: 3,
  contractsByCompany: 6.50,
  contractsByIndividualAndAop: 7,
  brokerageAndComissionByAdvertisementAgent: 10,
  brokerageAndComissionByLifeInsuranceAgent: 8,
  brokerageAndComissionByOtherCases: 12,
  profitOnDebtByInAllCases: 15,
  dividendByReceivedFromMutualFundsAndOthers: 15,
  dividendByReceivedFromCompanies: 25,
  immovablePropertyByAdvanceTaxOnBuyer: 1,
  immovablePropertyByAdvanceTaxOnSellerHoldingPeriodWithin4Years: 1,
  immovablePropertyByAdvanceTaxOnSellerHoldingPeriodAfter4Years: 0,
  rentForImmovablePropertyUpto300000: 0,
  rentForImmovablePropertyUpto300000To600000: 5,
  rentForImmovablePropertyUpto600000To2000000: 10% + 15000,
  rentForImmovablePropertyUptoAbove2000000: "",
  rentForImmovablePropertyCompanies:25% + 155000,
  purchaseOfAirTicketsByDomesticAirTickets: 5,
  internationalAirTicketsByEconomicClass: 0,
  internationalAirTicketsByExecutiveFirstClass: 0,
  internationalAirTicketsByOthersExcludingEconomy: 0,
  CngBusiness: 4,
  prizeAndWiningsByOnPrizeBonds: 15,
  prizeAndWiningsByRaffle: 20,
  petroleumProducts: 12,
};
